<template>
  <main class="legal-page">
    <section class="legal-shell">
      <header class="legal-hero">
        <p class="eyebrow">Game Cast Network</p>
        <h1>Terms of Service</h1>
        <p class="effective-date">Effective Date: June 30, 2026</p>
        <p>
          These Terms govern use of the Game Cast Network Live Dashboard, Live Viewer Count, and
          Sheet Sync tools for authorized social analytics, live metrics, and Google Sheet reporting.
        </p>
        <div class="legal-actions">
          <RouterLink to="/privacy_policy">Privacy Policy</RouterLink>
          <a href="mailto:yonefang@gamecastnetwork.com">Contact support</a>
        </div>
      </header>

      <section class="legal-card">
        <h2>1. Acceptance</h2>
        <p>
          By accessing or using the app, connecting an account, authorizing platform permissions, or
          running a Sheet Sync, you agree to these Terms and our Privacy Policy. If you do not agree,
          do not use the app.
        </p>
      </section>

      <section class="legal-card">
        <h2>2. Service Description</h2>
        <p>
          The app helps authorized users retrieve live viewer counts, live stream performance, and
          post-performance data from Facebook, Instagram, YouTube, TikTok, and Google APIs, then
          display that data in dashboards or sync it to a Google Sheet selected by the user.
        </p>
        <p>
          The Live Viewer Count feature periodically collects viewer count snapshots from authorized
          Facebook Live videos and YouTube live broadcasts that you connect, select, or authorize for
          monitoring during live events.
        </p>
        <p>
          The app is a reporting and workflow tool. It does not replace the official analytics,
          creator, business, advertising, or account-management interfaces provided by each platform.
        </p>
      </section>

      <section class="legal-card">
        <h2>3. Platform Terms</h2>
        <p>
          When you connect a third-party platform, you are also responsible for complying with that
          platform's terms, policies, API rules, and permission requirements.
        </p>
        <ul>
          <li>Facebook and Instagram features are subject to <a href="https://developers.facebook.com/terms/" target="_blank" rel="noopener noreferrer">Meta platform terms</a>, <a href="https://developers.facebook.com/policy/" target="_blank" rel="noopener noreferrer">Meta developer policies</a>, and applicable Graph API rules.</li>
          <li>YouTube features use YouTube API Services. By using YouTube-connected features, you agree to be bound by the <a href="https://www.youtube.com/t/terms" target="_blank" rel="noopener noreferrer">YouTube Terms of Service</a>.</li>
          <li>Google Sheets and Google account features are subject to Google terms, the <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google Privacy Policy</a>, and the <a href="https://developers.google.com/terms/api-services-user-data-policy" target="_blank" rel="noopener noreferrer">Google API Services User Data Policy</a>.</li>
          <li>TikTok features are subject to TikTok developer, business, and platform API terms applicable to your account and permissions, including the <a href="https://developers.tiktok.com/doc/our-guidelines-developer-guidelines" target="_blank" rel="noopener noreferrer">TikTok Developer Guidelines</a>.</li>
        </ul>
      </section>

      <section class="legal-card">
        <h2>4. Account Authorization</h2>
        <p>
          You may only connect accounts, pages, channels, profiles, Google Sheets, or other resources
          that you own, manage, or are authorized to access. You are responsible for maintaining
          correct permissions, revoking access when no longer needed, and ensuring that people in
          your organization have permission to view synced reports.
        </p>
      </section>

      <section class="legal-card">
        <h2>5. Acceptable Use</h2>
        <p>You agree not to use the app to:</p>
        <ul>
          <li>Access, sync, export, or share data from accounts you are not authorized to manage.</li>
          <li>Sell, broker, rent, or misuse platform data, tokens, insights, or reports.</li>
          <li>Use platform data for unrelated advertising, profiling, surveillance, discrimination, or unlawful purposes.</li>
          <li>Bypass platform permissions, rate limits, security controls, review requirements, or API restrictions.</li>
          <li>Upload malicious code, interfere with the app, or attempt to access systems, secrets, or data without authorization.</li>
          <li>Misrepresent reports or live viewer counts as official platform statements when they are generated by this app from available API responses.</li>
        </ul>
      </section>

      <section class="legal-card">
        <h2>6. Google Sheets Sync</h2>
        <p>
          Sheet Sync writes data into the Google Sheet and tabs you configure. You are responsible
          for the accuracy of Sheet IDs, tab names, sharing permissions, formulas, formatting, and
          who can access the Sheet after data is written.
        </p>
        <p>
          If a platform API delays, withholds, deprecates, or changes a metric, the app may show a
          blank value, dash, warning, cached value, or API error instead of the metric.
        </p>
      </section>

      <section class="legal-card">
        <h2>7. Live Viewer Count Collection</h2>
        <p>
          You may only use live viewer count collection for Facebook Live videos, YouTube live
          broadcasts, channels, pages, or events that you own, manage, or are authorized to monitor.
          You are responsible for confirming that event organizers, clients, and account owners have
          approved the monitoring and reporting workflow.
        </p>
        <p>
          Live viewer count snapshots are collected from platform API responses at collection times
          determined by the app, schedule, or user action. The app may store collection timestamps,
          stream identifiers, account identifiers, returned viewer counts, and related operational
          logs so that live event reporting can be reviewed after the broadcast.
        </p>
      </section>

      <section class="legal-card">
        <h2>8. Metrics and Availability</h2>
        <p>
          Social platform analytics can be delayed, sampled, restricted, unavailable, deprecated, or
          different from what appears in the platform's native interface. We do not guarantee that
          every metric, date range, content type, or live value will be available for every account.
          Facebook and YouTube live viewer counts may only be available while a broadcast is live or
          while the platform API continues to return live data.
        </p>
      </section>

      <section class="legal-card">
        <h2>9. Security</h2>
        <p>
          You must keep your accounts, service account files, app credentials, tokens, and Google
          Sheets secure. Notify us promptly if you believe unauthorized access has occurred.
        </p>
      </section>

      <section class="legal-card">
        <h2>10. Privacy and Data Deletion</h2>
        <p>
          Our Privacy Policy explains what data we collect, how we use it, and how to request data
          deletion. You can review it at
          <RouterLink to="/privacy_policy">/privacy_policy</RouterLink>.
        </p>
      </section>

      <section class="legal-card">
        <h2>11. Suspension or Termination</h2>
        <p>
          We may suspend or terminate access if use of the app violates these Terms, platform rules,
          security requirements, legal obligations, or creates risk for users, platforms, or our
          service. You may stop using the app or revoke connected account access at any time.
        </p>
      </section>

      <section class="legal-card">
        <h2>12. Disclaimers</h2>
        <p>
          The app is provided on an "as is" and "as available" basis. To the extent permitted by
          law, we disclaim warranties of merchantability, fitness for a particular purpose,
          uninterrupted availability, and non-infringement.
        </p>
      </section>

      <section class="legal-card">
        <h2>13. Limitation of Liability</h2>
        <p>
          To the extent permitted by law, Game Cast Network will not be liable for indirect,
          incidental, consequential, special, exemplary, or punitive damages, or for lost profits,
          lost revenue, lost data, business interruption, or platform API changes.
        </p>
      </section>

      <section class="legal-card">
        <h2>14. Changes to These Terms</h2>
        <p>
          We may update these Terms from time to time. Updated Terms will be posted on this page with
          a revised effective date. Continued use of the app after changes means you accept the
          updated Terms.
        </p>
      </section>

      <section class="legal-card">
        <h2>15. Contact</h2>
        <p>
          For questions about these Terms, contact
          <a href="mailto:yonefang@gamecastnetwork.com">yonefang@gamecastnetwork.com</a>.
        </p>
      </section>
    </section>
  </main>
</template>

<style lang="css" scoped>
.legal-page {
  background: #0f1727;
  color: #dbe7f5;
  min-height: 100vh;
  padding: 32px 18px 56px;
}

.legal-shell {
  margin: 0 auto;
  max-width: 980px;
}

.legal-hero,
.legal-card {
  background: #172239;
  border: 1px solid #31415f;
  border-radius: 8px;
  box-shadow: 0 18px 45px rgba(0, 0, 0, 0.22);
}

.legal-hero {
  margin-bottom: 18px;
  padding: 34px;
}

.eyebrow {
  color: #38bdf8;
  font-size: 0.82rem;
  font-weight: 800;
  letter-spacing: 0;
  margin: 0 0 10px;
  text-transform: uppercase;
}

h1,
h2 {
  color: #ffffff;
  line-height: 1.2;
  margin: 0;
}

h1 {
  font-size: 2.4rem;
}

h2 {
  font-size: 1.16rem;
  margin-bottom: 12px;
}

.effective-date {
  color: #9fb0c8;
  font-weight: 700;
  margin: 12px 0 14px;
}

p,
li {
  color: #c3d0e2;
  line-height: 1.68;
}

p {
  margin: 0 0 12px;
}

ul {
  margin: 12px 0 0;
  padding-left: 22px;
}

li + li {
  margin-top: 8px;
}

a {
  color: #7dd3fc;
  font-weight: 800;
  text-decoration: none;
}

a:hover {
  color: #ffffff;
}

.legal-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  margin-top: 22px;
}

.legal-actions a {
  background: #22314a;
  border-radius: 8px;
  color: #dbe7f5;
  display: inline-flex;
  min-height: 42px;
  padding: 10px 14px;
}

.legal-card {
  margin-bottom: 14px;
  padding: 24px;
}

@media (max-width: 640px) {
  .legal-page {
    padding: 18px 12px 36px;
  }

  .legal-hero,
  .legal-card {
    padding: 20px;
  }

  h1 {
    font-size: 1.9rem;
  }
}
</style>
